env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules: {
  no-console: off,
  import/extensions: 0,
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
}
